#include <ros/ros.h>
#include <std_msgs/String.h>

int main(int argc, char **argv)
{
    ros::init(argc, argv, "faradars_cpp_publisher_node");
    ros::NodeHandle nh;

    ros::Publisher pub=nh.advertise<std_msgs::String>("/cpp_msg",10);

    ros::Rate rate(2);

    while(ros::ok()){
        std_msgs::String msg;
        msg.data="This message is generated by cpp";
        pub.publish(msg);
        rate.sleep();
    }


}
